### ISSUE TITLE
findRelLink does not work with cached headers

### ISSUE THREAD

**Issue by Fil** [observablehq/oss-analytics#8]
https://github.com/observablehq/oss-analytics/blob/96b2248a435b0e01352eeb5a9cdd78ab1da5258a/src/github.js#L70

this breaks if the headers are taken from the cache; I think the following works in both cases:

```diff
-  return headers
-    .get("link")
+  headers = { ...headers };
+  return headers["link"]
```

**Comment by mbostock** [comment]
Fixed in 2ed5e5bf96a42a0af869d968e06d9ec057741786.
